[package]
name = "bevy_game"
version = "0.1.0"
edition = "2021"

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = "0.14.0"
bevy_rapier3d = {version = "0.27.0", features = ["simd-stable", "debug-render-3d"]}
